// test_environment.cpp — runtime chunk load/unload behind EnvironmentSource
// (VM-052). Same "no Filament type" boundary as every other tests/*.cpp --
// see environment_test_hooks.hpp.
#include "visual_renderer/api.h"
#include "visual_renderer/scene.h"

#include "environment_test_hooks.hpp"
#include "golden.hpp"
#include "test_paths.hpp"

#include <gtest/gtest.h>

#include <chrono>
#include <iostream>
#include <string>
#include <vector>

namespace {

const std::string kTestTownDir =
    std::string(MPVIZ_TEST_DATA_DIR) + "/tests/fixtures/environment_test_town_0";

// The fixture's own baked chunk centers (index.yaml, generated by Task 2's
// bake_environment.py against the committed Overpass cache -- see this
// file's own bottom-of-file provenance note).
constexpr mpviz::Vec3 kChunk0Center{-128.0, -128.0, 0.0};
// Well outside both chunks' kUnloadRadiusM (400 m) from either fixture
// chunk center.
constexpr mpviz::Vec3 kFarFromTown{100000.0, 100000.0, 0.0};

// The golden's own camera target: the real centroid of chunk_-1_-1's two
// baked footprints (measured directly from the fixture .glb, not the
// index.yaml chunk-cell center above -- a chunk's nominal center is its
// QUADTREE CELL's center, Task 2's own bake_environment.py convention,
// which need not coincide with where a real footprint happens to sit
// inside that cell).
constexpr mpviz::Vec3 kBuildingsCentroid{-109.2, -17.1, 3.0};

}  // namespace

TEST(Environment, SetEnvironmentSourceWithMissingDirIsNonFatal) {
    mpviz::RenderConfig cfg{320, 240, 1, kThemeDir, "dark_adas"};
    mpviz::CameraPose pose{{0, -8, 3}, {0, 0, 0.5}, 60};
    auto* r = mpviz::create_renderer(cfg);
    if (!r) GTEST_SKIP() << "no GPU/EGL";
    mpviz::GeoAnchor a{25.0803, 55.3910, 0.0};
    EXPECT_FALSE(mpviz::set_environment_source(r, "/nonexistent/path", a));

    // A missing environment source degrades to "no buildings," not a crash
    // or a failed frame (spec §9).
    std::vector<uint8_t> buf(320 * 240 * 3);
    EXPECT_TRUE(mpviz::render_frame(r, pose, {buf.data(), 320, 240}));
    mpviz::destroy_renderer(r);
}

TEST(Environment, NullSourceUriIsANoOpNotAConfigError) {
    mpviz::RenderConfig cfg{320, 240, 1, kThemeDir, "dark_adas"};
    auto* r = mpviz::create_renderer(cfg);
    if (!r) GTEST_SKIP() << "no GPU/EGL";
    EXPECT_FALSE(mpviz::set_environment_source(r, nullptr, mpviz::GeoAnchor{}));
    EXPECT_FALSE(mpviz::set_environment_source(r, "", mpviz::GeoAnchor{}));
    mpviz::destroy_renderer(r);
}

TEST(Environment, ChunksWithinLoadRadiusOfEgoAreRenderedAsThemedClay) {
    mpviz::RenderConfig cfg{320, 240, 1, kThemeDir, "dark_adas"};
    mpviz::CameraPose pose{{0, -8, 3}, {0, 0, 0.5}, 60};
    auto* r = mpviz::create_renderer(cfg);
    if (!r) GTEST_SKIP() << "no GPU/EGL";
    mpviz::GeoAnchor a{25.0803, 55.3910, 0.0};
    ASSERT_TRUE(mpviz::set_environment_source(r, kTestTownDir.c_str(), a));

    mpviz::SceneGraph s{};
    s.ego.valid = 1;
    s.ego.position = kChunk0Center;
    mpviz::set_scene(r, s);
    std::vector<uint8_t> buf(320 * 240 * 3);
    // Assertion below is via the Filament-free count hook, not a pixel
    // comparison, so this test doesn't need a chunk-framing camera -- the
    // same standard `pose` used throughout this suite is sufficient.
    ASSERT_TRUE(mpviz::render_frame(r, pose, {buf.data(), 320, 240}));
    EXPECT_GT(mpviz::testing::environment_loaded_chunk_count(r), 0u);
    mpviz::destroy_renderer(r);
}

TEST(Environment, ChunksFarFromEgoAreNotLoaded) {
    mpviz::RenderConfig cfg{320, 240, 1, kThemeDir, "dark_adas"};
    mpviz::CameraPose pose{{0, -8, 3}, {0, 0, 0.5}, 60};
    auto* r = mpviz::create_renderer(cfg);
    if (!r) GTEST_SKIP() << "no GPU/EGL";
    mpviz::GeoAnchor a{25.0803, 55.3910, 0.0};
    ASSERT_TRUE(mpviz::set_environment_source(r, kTestTownDir.c_str(), a));

    mpviz::SceneGraph s{};
    s.ego.valid = 1;
    s.ego.position = kFarFromTown;
    mpviz::set_scene(r, s);
    std::vector<uint8_t> buf(320 * 240 * 3);
    ASSERT_TRUE(mpviz::render_frame(r, pose, {buf.data(), 320, 240}));
    // Proves the cull gates LOADING, not merely drawing -- nothing was ever
    // pulled onto the GPU for a chunk this far away, not just "not visible
    // this frame."
    EXPECT_EQ(mpviz::testing::environment_loaded_chunk_count(r), 0u);
    mpviz::destroy_renderer(r);
}

TEST(Environment, InvalidEgoFreezesLoadedChunkCount) {
    mpviz::RenderConfig cfg{320, 240, 1, kThemeDir, "dark_adas"};
    mpviz::CameraPose pose{{0, -8, 3}, {0, 0, 0.5}, 60};
    auto* r = mpviz::create_renderer(cfg);
    if (!r) GTEST_SKIP() << "no GPU/EGL";
    mpviz::GeoAnchor a{25.0803, 55.3910, 0.0};
    ASSERT_TRUE(mpviz::set_environment_source(r, kTestTownDir.c_str(), a));

    mpviz::SceneGraph s{};
    s.ego.valid = 1;
    s.ego.position = kChunk0Center;
    mpviz::set_scene(r, s);
    std::vector<uint8_t> buf(320 * 240 * 3);
    ASSERT_TRUE(mpviz::render_frame(r, pose, {buf.data(), 320, 240}));
    const uint64_t loadedBefore = mpviz::testing::environment_loaded_chunk_count(r);
    ASSERT_GT(loadedBefore, 0u);

    // ego.valid == 0 (no TF yet this tick) -- render_frame() must not crash,
    // and the loaded-chunk count must stay exactly what it was: a tick with
    // no valid ego position leaves whatever's already loaded untouched
    // (freeze-frame, Task 3 Step 2), even though the new position below
    // would otherwise trigger an unload.
    s.ego.valid = 0;
    s.ego.position = kFarFromTown;
    mpviz::set_scene(r, s);
    ASSERT_TRUE(mpviz::render_frame(r, pose, {buf.data(), 320, 240}));
    EXPECT_EQ(mpviz::testing::environment_loaded_chunk_count(r), loadedBefore);
    mpviz::destroy_renderer(r);
}

// ── Step 4: theme token + golden (one theme -- P3 golden scoping, this is a
//    lit-geometry category golden like HUD/callouts/PointCloud, not a
//    theming-focused one) ────────────────────────────────────────────────────
TEST(EnvironmentGolden, TestTown_DarkAdas) {
    mpviz::RenderConfig cfg{320, 240, 1, kThemeDir, "dark_adas"};
    auto* r = mpviz::create_renderer(cfg);
    if (!r) GTEST_SKIP() << "no GPU/EGL";
    mpviz::GeoAnchor a{25.0803, 55.3910, 0.0};
    ASSERT_TRUE(mpviz::set_environment_source(r, kTestTownDir.c_str(), a));

    mpviz::SceneGraph s{};
    s.ego.valid = 1;
    s.ego.position = kChunk0Center;
    mpviz::set_scene(r, s);

    // Framed on the real footprint centroid (kBuildingsCentroid), not the
    // chunk cell's nominal center -- see that constant's own comment.
    mpviz::CameraPose pose{{kBuildingsCentroid.x + 50, kBuildingsCentroid.y - 70, 40},
                            {kBuildingsCentroid.x, kBuildingsCentroid.y, kBuildingsCentroid.z},
                            60.0};
    // One render to trigger the load before the golden comparison render --
    // render_and_compare() below re-renders internally, and by then the
    // chunk is already loaded (loading doesn't depend on which render call
    // triggers it, only on ego.valid/position already being published).
    std::vector<uint8_t> warm(320u * 240u * 3u);
    ASSERT_TRUE(mpviz::render_frame(r, pose, {warm.data(), 320, 240}));
    ASSERT_GT(mpviz::testing::environment_loaded_chunk_count(r), 0u);

    double ssim = mpviz::testing::render_and_compare(
        r, pose, MPVIZ_TEST_DATA_DIR "/tests/goldens/environment_test_town_dark_adas.png",
        "/tmp/environment_test_town_dark_adas_actual.png");
    EXPECT_GT(ssim, 0.98);
    mpviz::destroy_renderer(r);
}

// ── Step 5: perf check (dev-box proxy, AC: < 2 ms render_ms delta) ──────────
// Recorded, not hard-asserted: GPU timing on a shared dev box can flake
// under contention (this session's own instructions name two other suites
// running concurrently on this GPU) -- a strict assertion here would be
// exactly the kind of flaky gate that erodes trust in this suite. The
// measured delta is reported in this task's results block instead.
TEST(EnvironmentPerf, RenderMsDeltaWithTestTownLoaded) {
    mpviz::RenderConfig cfg{320, 240, 1, kThemeDir, "dark_adas"};
    mpviz::CameraPose pose{{kChunk0Center.x + 40, kChunk0Center.y - 60, 35},
                            {kChunk0Center.x, kChunk0Center.y, 2},
                            60.0};
    std::vector<uint8_t> buf(320u * 240u * 3u);
    constexpr int kFrames = 30;

    auto measure = [&](bool withEnvironment) -> double {
        auto* r = mpviz::create_renderer(cfg);
        if (!r) return -1.0;
        if (withEnvironment) {
            mpviz::GeoAnchor a{25.0803, 55.3910, 0.0};
            mpviz::set_environment_source(r, kTestTownDir.c_str(), a);
        }
        mpviz::SceneGraph s{};
        s.ego.valid = 1;
        s.ego.position = kChunk0Center;
        mpviz::set_scene(r, s);
        mpviz::render_frame(r, pose, {buf.data(), 320, 240});  // warm-up: first load
        const auto t0 = std::chrono::steady_clock::now();
        for (int i = 0; i < kFrames; ++i) {
            mpviz::render_frame(r, pose, {buf.data(), 320, 240});
        }
        const auto t1 = std::chrono::steady_clock::now();
        mpviz::destroy_renderer(r);
        return std::chrono::duration<double, std::milli>(t1 - t0).count() / kFrames;
    };

    const double withEnv = measure(/*withEnvironment=*/true);
    if (withEnv < 0.0) GTEST_SKIP() << "no GPU/EGL";
    const double withoutEnv = measure(/*withEnvironment=*/false);
    std::cerr << "[EnvironmentPerf] mean render_ms without=" << withoutEnv
              << " with=" << withEnv << " delta=" << (withEnv - withoutEnv) << " ms\n";
    SUCCEED();
}

// Fixture provenance (Step 1): tests/fixtures/environment_test_town_0/ was
// produced by running Task 2 (VM-051)'s bake_environment.py directly
// (read-only, from the concurrently-developed vm051 worktree) against its
// own committed Overpass cache fixture (environment_overpass_cache_0.json),
// anchor {25.0803, 55.3910, 0.0} -- 2 real baked chunks (chunk_-1_-1,
// chunk_-1_0), not hand-authored geometry. See this task's own results/
// deviation notes for the exact command and script commit.
