# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Amer Ghazal
#
# Target (CMAKE_SYSTEM_NAME, arch, sdk) -> overlay triplet in vcpkg-triplets/.
# sdk is only meaningful for iOS ("iphonesimulator" selects the simulator).
function(overlume_cesium_triplet out system arch sdk)
    if(arch MATCHES "^(x86_64|AMD64|x64)$")
        set(_a x64)
    elseif(arch MATCHES "^(aarch64|arm64|ARM64|arm64-v8a)$")
        set(_a arm64)
    elseif(arch MATCHES "^(armeabi-v7a|arm)$")
        set(_a arm)
    elseif(arch MATCHES "^(x86|i686)$")
        set(_a x86)
    else()
        message(FATAL_ERROR "overlume: no cesium triplet for architecture '${arch}'")
    endif()
    if(system STREQUAL "Linux")
        set(_t "${_a}-linux-clang-libcxx")
    elseif(system STREQUAL "Android")
        set(_t "${_a}-android-overlume")
    elseif(system STREQUAL "Darwin")
        set(_t "${_a}-osx-overlume")
    elseif(system STREQUAL "iOS")
        if(sdk MATCHES "simulator")
            set(_t "${_a}-ios-simulator-overlume")
        else()
            set(_t "${_a}-ios-overlume")
        endif()
    elseif(system STREQUAL "Windows")
        set(_t "${_a}-windows-overlume")
    else()
        message(FATAL_ERROR "overlume: no cesium triplet for system '${system}'")
    endif()
    set(${out} "${_t}" PARENT_SCOPE)
endfunction()
