# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Amer Ghazal

if(DEFINED ENV{XDG_CACHE_HOME} AND NOT "$ENV{XDG_CACHE_HOME}" STREQUAL "")
    set(_overlume_c18_cache_home "$ENV{XDG_CACHE_HOME}")
else()
    set(_overlume_c18_cache_home "$ENV{HOME}/.cache")
endif()
set(_overlume_clang18_prefix "${_overlume_c18_cache_home}/overlume-toolchain-cesium")
set(_overlume_clang18_real_clangxx "${_overlume_clang18_prefix}/root/usr/lib/llvm-18/bin/clang++")
set(_overlume_clang18_real_clang "${_overlume_clang18_prefix}/root/usr/lib/llvm-18/bin/clang")
set(_overlume_clang18_libdir1 "${_overlume_clang18_prefix}/root/usr/lib/llvm-18/lib")
set(_overlume_clang18_libdir2 "${_overlume_clang18_prefix}/root/usr/lib/x86_64-linux-gnu")
# Release layout (toolchain-llvm-release.cmake): the official LLVM tarball.
if(DEFINED ENV{OVERLUME_LLVM_ROOT} AND NOT "$ENV{OVERLUME_LLVM_ROOT}" STREQUAL "")
    set(_overlume_clang18_real_clangxx "$ENV{OVERLUME_LLVM_ROOT}/bin/clang++")
    set(_overlume_clang18_real_clang "$ENV{OVERLUME_LLVM_ROOT}/bin/clang")
    set(_overlume_clang18_libdir1 "$ENV{OVERLUME_LLVM_ROOT}/lib/${CMAKE_HOST_SYSTEM_PROCESSOR}-unknown-linux-gnu")
    set(_overlume_clang18_libdir2 "$ENV{OVERLUME_LLVM_ROOT}/lib")
endif()

if(NOT EXISTS "${_overlume_clang18_real_clangxx}")
    message(FATAL_ERROR
        "overlume: clang-18 not found at ${_overlume_clang18_real_clangxx}. "
        "Run scripts/setup_toolchain_cesium.sh first (bootstraps a rootless "
        "clang-18 from apt.llvm.org -- see that script's header comment for "
        "why clang-18 specifically; VM-061 Step 6 made it the PRIMARY "
        "toolchain, not just the vcpkg/cesium one).")
endif()

# Release wrappers get their own dir: the dev build's CMAKE_CXX_COMPILER points
# at wrap/clang++, which a release configure on the same host must never rewrite.
set(_overlume_clang18_wrap_dir "${_overlume_clang18_prefix}/wrap")
if(DEFINED ENV{OVERLUME_LLVM_ROOT} AND NOT "$ENV{OVERLUME_LLVM_ROOT}" STREQUAL "")
    set(_overlume_clang18_wrap_dir "${_overlume_clang18_prefix}/wrap-llvm-release")
endif()
file(MAKE_DIRECTORY "${_overlume_clang18_wrap_dir}")
set(_overlume_clang18_wrap_clangxx "${_overlume_clang18_wrap_dir}/clang++")
set(_overlume_clang18_wrap_clang "${_overlume_clang18_wrap_dir}/clang")
# file(CONFIGURE) rewrites only when the content changes: parallel configures
# (and every try_compile re-include) must not overwrite a wrapper another
# process is executing (ETXTBSY).
file(CONFIGURE OUTPUT "${_overlume_clang18_wrap_clangxx}" @ONLY CONTENT
"#!/bin/sh
# Generated by clang18-toolchain-common.cmake -- always libc++-18, always
# carries this rootless prefix's own LD_LIBRARY_PATH.
export LD_LIBRARY_PATH=\"${_overlume_clang18_libdir1}:${_overlume_clang18_libdir2}\${LD_LIBRARY_PATH:+:\$LD_LIBRARY_PATH}\"
exec \"${_overlume_clang18_real_clangxx}\" -stdlib=libc++ \"\$@\"
")
execute_process(COMMAND chmod +x "${_overlume_clang18_wrap_clangxx}")
file(CONFIGURE OUTPUT "${_overlume_clang18_wrap_clang}" @ONLY CONTENT
"#!/bin/sh
# Generated by clang18-toolchain-common.cmake.
export LD_LIBRARY_PATH=\"${_overlume_clang18_libdir1}:${_overlume_clang18_libdir2}\${LD_LIBRARY_PATH:+:\$LD_LIBRARY_PATH}\"
exec \"${_overlume_clang18_real_clang}\" \"\$@\"
")
execute_process(COMMAND chmod +x "${_overlume_clang18_wrap_clang}")
