// test_environment.cpp — runtime chunk load/unload behind EnvironmentSource
// (VM-052). Same "no Filament type" boundary as every other tests/*.cpp --
// see environment_test_hooks.hpp.
#include "visual_renderer/api.h"
#include "visual_renderer/scene.h"

#include "environment_test_hooks.hpp"
#include "golden.hpp"
#include "test_paths.hpp"

#include <gtest/gtest.h>

#include <chrono>
#include <cstdlib>
#include <iostream>
#include <string>
#include <vector>

namespace {

const std::string kTestTownDir =
    std::string(MPVIZ_TEST_DATA_DIR) + "/tests/fixtures/environment_test_town_0";

// The fixture's own baked chunk centers (index.yaml, generated by Task 2's
// bake_environment.py against the committed Overpass cache -- see this
// file's own bottom-of-file provenance note).
constexpr mpviz::Vec3 kChunk0Center{-128.0, -128.0, 0.0};
// Well outside both chunks' kUnloadRadiusM (400 m) from either fixture
// chunk center.
constexpr mpviz::Vec3 kFarFromTown{100000.0, 100000.0, 0.0};

// The golden's own camera target: the real centroid of chunk_-1_-1's two
// baked footprints (measured directly from the fixture .glb, not the
// index.yaml chunk-cell center above -- a chunk's nominal center is its
// QUADTREE CELL's center, Task 2's own bake_environment.py convention,
// which need not coincide with where a real footprint happens to sit
// inside that cell).
constexpr mpviz::Vec3 kBuildingsCentroid{-109.2, -17.1, 3.0};

}  // namespace

TEST(Environment, SetEnvironmentSourceWithMissingDirIsNonFatal) {
    mpviz::RenderConfig cfg{320, 240, 1, kThemeDir, "dark_adas"};
    mpviz::CameraPose pose{{0, -8, 3}, {0, 0, 0.5}, 60};
    auto* r = mpviz::create_renderer(cfg);
    if (!r) GTEST_SKIP() << "no GPU/EGL";
    mpviz::GeoAnchor a{25.0803, 55.3910, 0.0};
    EXPECT_FALSE(mpviz::set_environment_source(r, "/nonexistent/path", a));

    // A missing environment source degrades to "no buildings," not a crash
    // or a failed frame (spec §9).
    std::vector<uint8_t> buf(320 * 240 * 3);
    EXPECT_TRUE(mpviz::render_frame(r, pose, {buf.data(), 320, 240}));
    mpviz::destroy_renderer(r);
}

TEST(Environment, NullSourceUriIsANoOpNotAConfigError) {
    mpviz::RenderConfig cfg{320, 240, 1, kThemeDir, "dark_adas"};
    auto* r = mpviz::create_renderer(cfg);
    if (!r) GTEST_SKIP() << "no GPU/EGL";
    EXPECT_FALSE(mpviz::set_environment_source(r, nullptr, mpviz::GeoAnchor{}));
    EXPECT_FALSE(mpviz::set_environment_source(r, "", mpviz::GeoAnchor{}));
    mpviz::destroy_renderer(r);
}

TEST(Environment, ChunksWithinLoadRadiusOfEgoAreRenderedAsThemedClay) {
    mpviz::RenderConfig cfg{320, 240, 1, kThemeDir, "dark_adas"};
    mpviz::CameraPose pose{{0, -8, 3}, {0, 0, 0.5}, 60};
    auto* r = mpviz::create_renderer(cfg);
    if (!r) GTEST_SKIP() << "no GPU/EGL";
    mpviz::GeoAnchor a{25.0803, 55.3910, 0.0};
    ASSERT_TRUE(mpviz::set_environment_source(r, kTestTownDir.c_str(), a));

    mpviz::SceneGraph s{};
    s.ego.valid = 1;
    s.ego.position = kChunk0Center;
    mpviz::set_scene(r, s);
    std::vector<uint8_t> buf(320 * 240 * 3);
    // Assertion below is via the Filament-free count hook, not a pixel
    // comparison, so this test doesn't need a chunk-framing camera -- the
    // same standard `pose` used throughout this suite is sufficient.
    ASSERT_TRUE(mpviz::render_frame(r, pose, {buf.data(), 320, 240}));
    EXPECT_GT(mpviz::testing::environment_loaded_chunk_count(r), 0u);
    mpviz::destroy_renderer(r);
}

TEST(Environment, ChunksFarFromEgoAreNotLoaded) {
    mpviz::RenderConfig cfg{320, 240, 1, kThemeDir, "dark_adas"};
    mpviz::CameraPose pose{{0, -8, 3}, {0, 0, 0.5}, 60};
    auto* r = mpviz::create_renderer(cfg);
    if (!r) GTEST_SKIP() << "no GPU/EGL";
    mpviz::GeoAnchor a{25.0803, 55.3910, 0.0};
    ASSERT_TRUE(mpviz::set_environment_source(r, kTestTownDir.c_str(), a));

    mpviz::SceneGraph s{};
    s.ego.valid = 1;
    s.ego.position = kFarFromTown;
    mpviz::set_scene(r, s);
    std::vector<uint8_t> buf(320 * 240 * 3);
    ASSERT_TRUE(mpviz::render_frame(r, pose, {buf.data(), 320, 240}));
    // Proves the cull gates LOADING, not merely drawing -- nothing was ever
    // pulled onto the GPU for a chunk this far away, not just "not visible
    // this frame."
    EXPECT_EQ(mpviz::testing::environment_loaded_chunk_count(r), 0u);
    mpviz::destroy_renderer(r);
}

TEST(Environment, HysteresisBandKeepsChunksLoadedThenUnloadsAndReloads) {
    mpviz::RenderConfig cfg{320, 240, 1, kThemeDir, "dark_adas"};
    mpviz::CameraPose pose{{0, -8, 3}, {0, 0, 0.5}, 60};
    auto* r = mpviz::create_renderer(cfg);
    if (!r) GTEST_SKIP() << "no GPU/EGL";
    mpviz::GeoAnchor a{25.0803, 55.3910, 0.0};
    ASSERT_TRUE(mpviz::set_environment_source(r, kTestTownDir.c_str(), a));

    std::vector<uint8_t> buf(320 * 240 * 3);
    mpviz::SceneGraph s{};
    s.ego.valid = 1;

    // The fixture has a SECOND chunk 256 m north of kChunk0Center
    // (chunk_-1_0) that would also load/unload alongside chunk_-1_-1 if the
    // ego walked straight out from kChunk0Center, muddying a single-chunk
    // hysteresis check. Basing every position below 150 m south of
    // kChunk0Center keeps the second chunk beyond kLoadRadiusM/
    // kUnloadRadiusM throughout (its distance from any position here is
    // always > 400 m), so this test isolates chunk_-1_-1's own load/band/
    // unload/reload transitions.
    const mpviz::Vec3 base{kChunk0Center.x, kChunk0Center.y - 150.0, kChunk0Center.z};

    // (1) 150 m from chunk_-1_-1's center -- loads.
    s.ego.position = base;
    mpviz::set_scene(r, s);
    ASSERT_TRUE(mpviz::render_frame(r, pose, {buf.data(), 320, 240}));
    ASSERT_EQ(mpviz::testing::environment_loaded_chunk_count(r), 1u);

    // (2) ~381 m from chunk_-1_-1's center -- inside the hysteresis band
    // (> kLoadRadiusM 300, < kUnloadRadiusM 400): an already-loaded chunk
    // must stay loaded. This is what fails if the two radii are ever
    // collapsed to one.
    s.ego.position = {base.x + 350.0, base.y, base.z};
    mpviz::set_scene(r, s);
    ASSERT_TRUE(mpviz::render_frame(r, pose, {buf.data(), 320, 240}));
    EXPECT_EQ(mpviz::testing::environment_loaded_chunk_count(r), 1u);

    // (3) ~522 m from chunk_-1_-1's center -- beyond kUnloadRadiusM: the
    // unload branch actually runs.
    s.ego.position = {base.x + 500.0, base.y, base.z};
    mpviz::set_scene(r, s);
    ASSERT_TRUE(mpviz::render_frame(r, pose, {buf.data(), 320, 240}));
    EXPECT_EQ(mpviz::testing::environment_loaded_chunk_count(r), 0u);

    // (4) Back at the 150 m base position -- reloads cleanly after teardown.
    s.ego.position = base;
    mpviz::set_scene(r, s);
    ASSERT_TRUE(mpviz::render_frame(r, pose, {buf.data(), 320, 240}));
    EXPECT_EQ(mpviz::testing::environment_loaded_chunk_count(r), 1u);

    mpviz::destroy_renderer(r);
}

// ── set_environment_visible() (VM-096): hide/show without teardown ─────────
//
// SSIM-against-a-fixed-golden (the pattern every other test in this file
// uses) turns out to be the WRONG tool for proving a hide/show toggle: the
// buildings occupy only part of the 320x240 frame, so removing them barely
// moves the whole-frame SSIM (measured ~0.972 hidden vs ~0.99+ shown against
// the SAME golden -- nowhere near a useful threshold). These tests instead
// diff RAW PIXEL BUFFERS against each other, which is exactly what a
// hide/show toggle needs proven: "this frame differs from that frame," not
// "this frame resembles a fixed reference."
namespace {
// Count of byte positions where two equal-sized RGB8 buffers differ by more
// than `tolerance` -- GPU rendering has a little bit-level dithering noise
// frame to frame even with a fully static scene/camera (observed: lone
// pixels off by 1), so an exact byte-for-byte compare is too strict for
// "these two frames show the same content." tolerance=1 absorbs that noise
// without hiding a real content change (buildings appearing/disappearing
// moves thousands of bytes by far more than 1).
size_t count_differing_bytes(const std::vector<uint8_t>& a, const std::vector<uint8_t>& b,
                              int tolerance = 1) {
    size_t n = 0;
    for (size_t i = 0; i < a.size() && i < b.size(); ++i) {
        if (std::abs(static_cast<int>(a[i]) - static_cast<int>(b[i])) > tolerance) ++n;
    }
    return n;
}
}  // namespace

TEST(Environment, SetEnvironmentVisibleNullRendererIsFalse) {
    EXPECT_FALSE(mpviz::set_environment_visible(nullptr, true));
    EXPECT_FALSE(mpviz::set_environment_visible(nullptr, false));
}

TEST(Environment, SetEnvironmentVisibleFalseHidesLoadedChunksWithoutTearingDown) {
    mpviz::RenderConfig cfg{320, 240, 1, kThemeDir, "dark_adas"};
    auto* r = mpviz::create_renderer(cfg);
    if (!r) GTEST_SKIP() << "no GPU/EGL";
    mpviz::GeoAnchor a{25.0803, 55.3910, 0.0};
    ASSERT_TRUE(mpviz::set_environment_source(r, kTestTownDir.c_str(), a));

    mpviz::SceneGraph s{};
    s.ego.valid = 1;
    s.ego.position = kChunk0Center;
    mpviz::set_scene(r, s);

    // Same framing as EnvironmentGolden.TestTown_DarkAdas -- frames the
    // real footprint centroid so the buildings occupy a real chunk of the
    // image, not a corner.
    mpviz::CameraPose pose{{kBuildingsCentroid.x + 50, kBuildingsCentroid.y - 70, 40},
                            {kBuildingsCentroid.x, kBuildingsCentroid.y, kBuildingsCentroid.z},
                            60.0};
    const size_t nBytes = 320u * 240u * 3u;
    std::vector<uint8_t> visibleBuf(nBytes);
    ASSERT_TRUE(mpviz::render_frame(r, pose, {visibleBuf.data(), 320, 240}));
    const uint64_t loadedBefore = mpviz::testing::environment_loaded_chunk_count(r);
    ASSERT_GT(loadedBefore, 0u);
    ASSERT_EQ(mpviz::testing::environment_scene_membership_count(r), loadedBefore);
    // Sanity check against the established golden: this IS the same known-
    // good visible frame every other test in this file already trusts.
    const double ssimVisible = mpviz::testing::render_and_compare(
        r, pose, MPVIZ_TEST_DATA_DIR "/tests/goldens/environment_test_town_dark_adas.png",
        "/tmp/environment_visible_before_hide_actual.png");
    ASSERT_GT(ssimVisible, 0.98);

    ASSERT_TRUE(mpviz::set_environment_visible(r, false));
    std::vector<uint8_t> hiddenBuf(nBytes);
    ASSERT_TRUE(mpviz::render_frame(r, pose, {hiddenBuf.data(), 320, 240}));
    // Not torn down: still "loaded" by the count hook (a re-show must not
    // need a re-fetch/re-bake) -- but zero of it is actually in the scene.
    EXPECT_EQ(mpviz::testing::environment_loaded_chunk_count(r), loadedBefore);
    EXPECT_EQ(mpviz::testing::environment_scene_membership_count(r), 0u);
    // At least 5% of the frame's bytes must have changed -- buildings
    // filling a real chunk of frame, now replaced by sky/ground, is a
    // large, unmistakable pixel delta, not sensor noise.
    const size_t diffHidden = count_differing_bytes(visibleBuf, hiddenBuf);
    EXPECT_GT(diffHidden, nBytes / 20)
        << "buildings still visible in the rendered frame after "
           "set_environment_visible(r, false) (only "
        << diffHidden << "/" << nBytes << " bytes changed)";

    // Re-show: same loaded chunks pop back without a reload, producing the
    // EXACT same frame as before hiding (static scene/camera/theme, no
    // TAA at this quality preset -- see ApplyQualityViewOptions).
    ASSERT_TRUE(mpviz::set_environment_visible(r, true));
    std::vector<uint8_t> shownAgainBuf(nBytes);
    ASSERT_TRUE(mpviz::render_frame(r, pose, {shownAgainBuf.data(), 320, 240}));
    EXPECT_EQ(mpviz::testing::environment_loaded_chunk_count(r), loadedBefore);
    EXPECT_EQ(mpviz::testing::environment_scene_membership_count(r), loadedBefore);
    // Threshold: measured noise from one hide/show round trip through the
    // SAME renderer (entities removed from and re-added to r.scene, which
    // can shift edge-antialiasing/AO sampling by a level or two at
    // silhouette pixels) is ~2.3% of bytes; a real "buildings still/again
    // missing" content loss measures ~7% (diffHidden above) -- nBytes/20
    // (5%) sits cleanly between the two with margin on both sides.
    const size_t diffShownAgain = count_differing_bytes(shownAgainBuf, visibleBuf);
    EXPECT_LT(diffShownAgain, nBytes / 20)
        << "re-showing produced a different frame than before hiding (" << diffShownAgain << "/"
        << nBytes << " bytes changed beyond dithering-level noise)";
    mpviz::destroy_renderer(r);
}

TEST(Environment, ChunkLoadedWhileHiddenDoesNotPopIntoView) {
    mpviz::RenderConfig cfg{320, 240, 1, kThemeDir, "dark_adas"};
    auto* r = mpviz::create_renderer(cfg);
    if (!r) GTEST_SKIP() << "no GPU/EGL";
    mpviz::GeoAnchor a{25.0803, 55.3910, 0.0};
    ASSERT_TRUE(mpviz::set_environment_source(r, kTestTownDir.c_str(), a));
    // Hidden BEFORE the ego ever gets close enough to load anything --
    // proves the load path itself checks visibility, not just a
    // post-hoc removeEntities on an already-visible chunk.
    ASSERT_TRUE(mpviz::set_environment_visible(r, false));

    mpviz::SceneGraph s{};
    s.ego.valid = 1;
    s.ego.position = kChunk0Center;
    mpviz::set_scene(r, s);
    mpviz::CameraPose pose{{kBuildingsCentroid.x + 50, kBuildingsCentroid.y - 70, 40},
                            {kBuildingsCentroid.x, kBuildingsCentroid.y, kBuildingsCentroid.z},
                            60.0};
    const size_t nBytes = 320u * 240u * 3u;
    std::vector<uint8_t> hiddenBuf(nBytes);
    ASSERT_TRUE(mpviz::render_frame(r, pose, {hiddenBuf.data(), 320, 240}));
    ASSERT_GT(mpviz::testing::environment_loaded_chunk_count(r), 0u)
        << "loading itself must still happen while hidden";
    EXPECT_EQ(mpviz::testing::environment_scene_membership_count(r), 0u)
        << "a chunk loaded while hidden was added to the Filament scene anyway";

    // Reference: a SECOND renderer, same theme/pose, that never had an
    // environment source at all -- the ground truth for "buildings not
    // rendered." Byte-identical to hiddenBuf proves the chunk that loaded
    // above never touched the Filament scene.
    auto* rNoEnv = mpviz::create_renderer(cfg);
    ASSERT_NE(rNoEnv, nullptr);
    // Same ego publish as `r` -- controls for the ego model's own presence
    // in the frame, so the ONLY variable left between the two renderers is
    // the environment source.
    mpviz::set_scene(rNoEnv, s);
    std::vector<uint8_t> noEnvBuf(nBytes);
    ASSERT_TRUE(mpviz::render_frame(rNoEnv, pose, {noEnvBuf.data(), 320, 240}));
    mpviz::destroy_renderer(rNoEnv);
    const size_t diffFromNoEnv = count_differing_bytes(hiddenBuf, noEnvBuf);
    EXPECT_LT(diffFromNoEnv, nBytes / 100)
        << "a chunk loaded while hidden popped into view (" << diffFromNoEnv << "/" << nBytes
        << " bytes differ from a renderer with no environment source at all)";

    ASSERT_TRUE(mpviz::set_environment_visible(r, true));
    std::vector<uint8_t> shownBuf(nBytes);
    ASSERT_TRUE(mpviz::render_frame(r, pose, {shownBuf.data(), 320, 240}));
    const size_t diffShown = count_differing_bytes(hiddenBuf, shownBuf);
    EXPECT_GT(diffShown, nBytes / 20)
        << "showing again produced no visible change (only " << diffShown << "/" << nBytes
        << " bytes changed)";
    EXPECT_EQ(mpviz::testing::environment_scene_membership_count(r),
              mpviz::testing::environment_loaded_chunk_count(r));
    mpviz::destroy_renderer(r);
}

TEST(Environment, SetEnvironmentVisibleFalseBeforeArmingHidesNewlyOpenedSource) {
    // VM-096 gate round 1 finding: the two tests above both call
    // set_environment_visible() AFTER a source is already open. This is the
    // other ordering the visualization_node fix actually depends on -- a
    // deployment launched with environment_enabled=false must end up with a
    // HIDDEN source once one is later armed (on_activate(), or a live
    // environment_source_uri switch), never a visible one just because
    // r->environmentVisible still sat at its raw default. Exercises
    // environment.cpp's set_environment_source() sync line directly
    // (`source->set_visible(*r, r->environmentVisible)`), the exact code the
    // node-level fix depends on.
    mpviz::RenderConfig cfg{320, 240, 1, kThemeDir, "dark_adas"};
    auto* r = mpviz::create_renderer(cfg);
    if (!r) GTEST_SKIP() << "no GPU/EGL";
    ASSERT_TRUE(mpviz::environment_visible(r)) << "default must be true before anyone touches it";

    // Hidden BEFORE set_environment_source() is ever called -- no source
    // exists yet (environment_source_state() == NONE).
    ASSERT_TRUE(mpviz::set_environment_visible(r, false));
    ASSERT_FALSE(mpviz::environment_visible(r));
    ASSERT_EQ(mpviz::environment_source_state(r), mpviz::EnvironmentSourceState::NONE);

    mpviz::GeoAnchor a{25.0803, 55.3910, 0.0};
    ASSERT_TRUE(mpviz::set_environment_source(r, kTestTownDir.c_str(), a));
    // The flag itself must still read false (set_environment_source() must
    // not silently reset it), AND the newly installed source must actually
    // come up hidden, not just bookkeeping-hidden.
    EXPECT_FALSE(mpviz::environment_visible(r));

    mpviz::SceneGraph s{};
    s.ego.valid = 1;
    s.ego.position = kChunk0Center;
    mpviz::set_scene(r, s);
    mpviz::CameraPose pose{{kBuildingsCentroid.x + 50, kBuildingsCentroid.y - 70, 40},
                            {kBuildingsCentroid.x, kBuildingsCentroid.y, kBuildingsCentroid.z},
                            60.0};
    const size_t nBytes = 320u * 240u * 3u;
    std::vector<uint8_t> hiddenBuf(nBytes);
    ASSERT_TRUE(mpviz::render_frame(r, pose, {hiddenBuf.data(), 320, 240}));
    ASSERT_GT(mpviz::testing::environment_loaded_chunk_count(r), 0u)
        << "loading itself must still happen while hidden";
    EXPECT_EQ(mpviz::testing::environment_scene_membership_count(r), 0u)
        << "a source armed while environmentVisible was already false came up visible anyway";

    // Now flip it live, same as the node's environment_enabled on_params()
    // branch (or the GUI switch) would: the buildings must actually appear.
    ASSERT_TRUE(mpviz::set_environment_visible(r, true));
    std::vector<uint8_t> shownBuf(nBytes);
    ASSERT_TRUE(mpviz::render_frame(r, pose, {shownBuf.data(), 320, 240}));
    const size_t diffShown = count_differing_bytes(hiddenBuf, shownBuf);
    EXPECT_GT(diffShown, nBytes / 20)
        << "showing produced no visible change (only " << diffShown << "/" << nBytes
        << " bytes changed)";
    EXPECT_EQ(mpviz::testing::environment_scene_membership_count(r),
              mpviz::testing::environment_loaded_chunk_count(r));
    mpviz::destroy_renderer(r);
}

TEST(Environment, InvalidEgoFreezesLoadedChunkCount) {
    mpviz::RenderConfig cfg{320, 240, 1, kThemeDir, "dark_adas"};
    mpviz::CameraPose pose{{0, -8, 3}, {0, 0, 0.5}, 60};
    auto* r = mpviz::create_renderer(cfg);
    if (!r) GTEST_SKIP() << "no GPU/EGL";
    mpviz::GeoAnchor a{25.0803, 55.3910, 0.0};
    ASSERT_TRUE(mpviz::set_environment_source(r, kTestTownDir.c_str(), a));

    mpviz::SceneGraph s{};
    s.ego.valid = 1;
    s.ego.position = kChunk0Center;
    mpviz::set_scene(r, s);
    std::vector<uint8_t> buf(320 * 240 * 3);
    ASSERT_TRUE(mpviz::render_frame(r, pose, {buf.data(), 320, 240}));
    const uint64_t loadedBefore = mpviz::testing::environment_loaded_chunk_count(r);
    ASSERT_GT(loadedBefore, 0u);

    // ego.valid == 0 (no TF yet this tick) -- render_frame() must not crash,
    // and the loaded-chunk count must stay exactly what it was: a tick with
    // no valid ego position leaves whatever's already loaded untouched
    // (freeze-frame, Task 3 Step 2), even though the new position below
    // would otherwise trigger an unload.
    s.ego.valid = 0;
    s.ego.position = kFarFromTown;
    mpviz::set_scene(r, s);
    ASSERT_TRUE(mpviz::render_frame(r, pose, {buf.data(), 320, 240}));
    EXPECT_EQ(mpviz::testing::environment_loaded_chunk_count(r), loadedBefore);
    mpviz::destroy_renderer(r);
}

// ── Step 4: theme token + golden (one theme -- P3 golden scoping, this is a
//    lit-geometry category golden like HUD/callouts/PointCloud, not a
//    theming-focused one) ────────────────────────────────────────────────────
TEST(EnvironmentGolden, TestTown_DarkAdas) {
    mpviz::RenderConfig cfg{320, 240, 1, kThemeDir, "dark_adas"};
    auto* r = mpviz::create_renderer(cfg);
    if (!r) GTEST_SKIP() << "no GPU/EGL";
    mpviz::GeoAnchor a{25.0803, 55.3910, 0.0};
    ASSERT_TRUE(mpviz::set_environment_source(r, kTestTownDir.c_str(), a));

    mpviz::SceneGraph s{};
    s.ego.valid = 1;
    s.ego.position = kChunk0Center;
    mpviz::set_scene(r, s);

    // Framed on the real footprint centroid (kBuildingsCentroid), not the
    // chunk cell's nominal center -- see that constant's own comment.
    mpviz::CameraPose pose{{kBuildingsCentroid.x + 50, kBuildingsCentroid.y - 70, 40},
                            {kBuildingsCentroid.x, kBuildingsCentroid.y, kBuildingsCentroid.z},
                            60.0};
    // One render to trigger the load before the golden comparison render --
    // render_and_compare() below re-renders internally, and by then the
    // chunk is already loaded (loading doesn't depend on which render call
    // triggers it, only on ego.valid/position already being published).
    std::vector<uint8_t> warm(320u * 240u * 3u);
    ASSERT_TRUE(mpviz::render_frame(r, pose, {warm.data(), 320, 240}));
    ASSERT_GT(mpviz::testing::environment_loaded_chunk_count(r), 0u);

    double ssim = mpviz::testing::render_and_compare(
        r, pose, MPVIZ_TEST_DATA_DIR "/tests/goldens/environment_test_town_dark_adas.png",
        "/tmp/environment_test_town_dark_adas_actual.png");
    EXPECT_GT(ssim, 0.98);
    mpviz::destroy_renderer(r);
}

// ── Step 5: perf check (dev-box proxy, AC: < 2 ms render_ms delta) ──────────
// Recorded, not hard-asserted: GPU timing on a shared dev box can flake
// under contention (this session's own instructions name two other suites
// running concurrently on this GPU) -- a strict assertion here would be
// exactly the kind of flaky gate that erodes trust in this suite. The
// measured delta is reported in this task's results block instead.
TEST(EnvironmentPerf, RenderMsDeltaWithTestTownLoaded) {
    mpviz::RenderConfig cfg{320, 240, 1, kThemeDir, "dark_adas"};
    mpviz::CameraPose pose{{kChunk0Center.x + 40, kChunk0Center.y - 60, 35},
                            {kChunk0Center.x, kChunk0Center.y, 2},
                            60.0};
    std::vector<uint8_t> buf(320u * 240u * 3u);
    constexpr int kFrames = 30;

    auto measure = [&](bool withEnvironment) -> double {
        auto* r = mpviz::create_renderer(cfg);
        if (!r) return -1.0;
        if (withEnvironment) {
            mpviz::GeoAnchor a{25.0803, 55.3910, 0.0};
            mpviz::set_environment_source(r, kTestTownDir.c_str(), a);
        }
        mpviz::SceneGraph s{};
        s.ego.valid = 1;
        s.ego.position = kChunk0Center;
        mpviz::set_scene(r, s);
        mpviz::render_frame(r, pose, {buf.data(), 320, 240});  // warm-up: first load
        const auto t0 = std::chrono::steady_clock::now();
        for (int i = 0; i < kFrames; ++i) {
            mpviz::render_frame(r, pose, {buf.data(), 320, 240});
        }
        const auto t1 = std::chrono::steady_clock::now();
        mpviz::destroy_renderer(r);
        return std::chrono::duration<double, std::milli>(t1 - t0).count() / kFrames;
    };

    const double withEnv = measure(/*withEnvironment=*/true);
    if (withEnv < 0.0) GTEST_SKIP() << "no GPU/EGL";
    const double withoutEnv = measure(/*withEnvironment=*/false);
    std::cerr << "[EnvironmentPerf] mean render_ms without=" << withoutEnv
              << " with=" << withEnv << " delta=" << (withEnv - withoutEnv) << " ms\n";
    SUCCEED();
}

// Fixture provenance (Step 1): tests/fixtures/environment_test_town_0/ was
// produced by running Task 2 (VM-051)'s bake_environment.py directly
// (read-only, from the concurrently-developed vm051 worktree) against its
// own committed Overpass cache fixture (environment_overpass_cache_0.json),
// anchor {25.0803, 55.3910, 0.0} -- 2 real baked chunks (chunk_-1_-1,
// chunk_-1_0), not hand-authored geometry. See this task's own results/
// deviation notes for the exact command and script commit.
//
// verification_overlay.png is the bake's own QA artifact, kept as-is from
// the --out dir; no test reads it.
